add password var; make output more meaningful

diff --git a/talosPluginUpload b/talosPluginUpload
--- a/talosPluginUpload
+++ b/talosPluginUpload
@@ -7,19 +7,29 @@
 ## sh talosPluginUpload ~/foo/ ~/install-list.txt example.com 22
 ##
 
+PASSWORD=${PASSWORD:-}
+
 for USER in `cat ${2}`; do
   lftp -c "open sftp://${3}:${4}
-    user ${USER}
-    set net:reconnect-interval-base 1
-    set net:reconnect-interval-base 1
+    user ${USER} ${PASSWORD}
+    set net:reconnect-interval-base 2
+    set net:reconnect-interval-max 2
     set net:max-retries 1
     mirror --reverse --delete --verbose ${1} /wp-content/plugins/"
-  echo "$USER complete."
+  if [ $? = 0 ]; then
+    echo "$USER complete."
+  else
+    echo "$USER failed."
+  fi
   lftp -c "open sftp://${3}:${4}
-    user ${USER}-staging
-    set net:reconnect-interval-base 1
-    set net:reconnect-interval-base 1
+    user ${USER}-staging ${PASSWORD}
+    set net:reconnect-interval-base 2
+    set net:reconnect-interval-max 2
     set net:max-retries 1
     mirror --reverse --delete --verbose ${1} /wp-content/plugins/"
-  echo "$USER-staging complete."
+  if [ $? = 0 ]; then
+    echo "$USER-staging complete."
+  else
+    echo "$USER-staging failed."
+  fi
 done
